---
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    restart: always
    networks:
      - frontend
      - backend

networks:
  frontend:
    external: true
  backend:
    external: true
