---
services:
  forgejo-server:
    container_name: forgejo-server
    image: codeberg.org/forgejo/forgejo:11
    restart: unless-stopped
    environment:
      USER_UID: $PUID
      USER_GID: $PGID
      # https://forgejo.org/docs/latest/admin/config-cheat-sheet/
      FORGEJO__repository__ENABLE_PUSH_CREATE_USER: true
      FORGEJO__service__DISABLE_REGISTRATION: true
      FORGEJO__server__SSH_PORT: $SSH_PORT
    volumes:
      - $VOLUME/forgejo/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      traefik.enable: true
      traefik.http.routers.forgejo-https.entrypoints: websecure
      traefik.http.routers.forgejo-https.rule: "Host(`${FQDN}`)"
      traefik.http.routers.forgejo-https.tls: true
      traefik.http.routers.forgejo-https.tls.certresolver: cloudflare
      # traefik.http.routers.forgejo-https.middlewares: tinyauth
      traefik.http.services.forgejo-https.loadbalancer.server.port: 3000
      com.centurylinklabs.watchtower.enable: true
    ports:
    - $SSH_PORT:22
    networks:
      - frontend

networks:
  frontend:
    external: true
